---
- name: Setup Nginx
  hosts: digitalocean
  remote_user: ansible
  become: yes
  gather_facts: no
  vars:
    ansible_ssh_private_key_file: "./ansible_rsa"
  tasks:
    - name: Get via apt
      apt:
        name: nginx
        state: latest
        update_cache: yes
    - name: Start service
      service: name=nginx state=started